<form name="adminForm" action="<?php echo $this->element->getAction(); ?>" 
method="<?php echo $this->element->getMethod(); ?>" enctype="multipart/form-data">


	Email:
	<?php echo $this->element->txtEmail; ?><br />
	
	Password:
	<?php echo $this->element->txtPassword; ?><br />
	
	Password confirm:
	<?php echo $this->element->txtPasswordConfirm; ?><br />
	
	Display Name:
	<?php echo $this->element->txtDisplayName; ?><br />
	
	Avatar:
	<?php echo $this->element->attachment; ?><br />
	
	<!-- 
	Address:
	<?php echo $this->element->txtAddress; ?><br />
	
	Phone:
	<?php echo $this->element->txtPhone; ?><br />
	
	
	
	Biography:
	<?php echo $this->element->txtBiography; ?><br />
	
	Twitter:
	<?php echo $this->element->txtTwitter; ?><br />
	
	Facebook:
	<?php echo $this->element->txtFacebook; ?><br />
	
	Privacy status:
	<?php echo $this->element->slPrivacyStatus; ?><br />
	 -->

	<button class="green" type="submit">Sign up</button>

</form>