<form name="adminForm" action="<?php echo $this->element->getAction(); ?>" 
method="<?php echo $this->element->getMethod(); ?>" enctype="multipart/form-data">

	Email:
	<?php echo $this->element->txtEmail; ?><br />
	
	Old Password:
	<?php echo $this->element->txtPasswordOld; ?><br />
	
	Password:
	<?php echo $this->element->txtPassword; ?><br />
	
	Password confirm:
	<?php echo $this->element->txtPasswordConfirm; ?><br />
	
	Display Name:
	<?php echo $this->element->txtDisplayName; ?><br />
	
	Current avatar:
	<?php echo $this->element->currentAvatar; ?><br />
	
	Avatar:
	<?php echo $this->element->attachment; ?><br />
	
	

	<button class="green" type="submit">Sign up</button>

</form>