<h2>List all of Users</h2>
<hr />

<div class="msg_errors">
	<ul>
	<?php $msgErrors = $this->msgErrors; ?>

	<?php
	if (count ( $msgErrors ) > 0) {
		?>
			<?php foreach ($this->msgErrors as $error) { ?>
						<li><?php echo $error; ?></li>	
			<?php
		
		}
	}
	?>
	</ul>
</div>
<script type="text/javascript">
<!--
/**
 * Toggles the check state of a group of boxes.
 * 
 * Checkboxes must have an id attribute in the form cb0, cb1...
 * 
 * @param The
 *            number of box to 'check'
 * @param An
 *            alternative field name
 */
function checkAll(n) {
	

	fldName = 'cb';

	var f = document.adminForm;
	var c = f.toggle.checked;
	var n2 = 0;
	for (i = 1; i <= n; i++) {
		cb = eval('f.' + fldName + '' + i);

		if (cb) {
			cb.checked = c;
			n2++;
		}

	}
	if (c) {
		document.adminForm.boxchecked.value = n2;
	} else {
		document.adminForm.boxchecked.value = 0;
	}
}

function isChecked(isitchecked) {
	
	
	if (isitchecked == true) {
		document.adminForm.boxchecked.value++;
	} else {
		document.adminForm.boxchecked.value--;
	}
}
function checkThis(cb) {
	var f = document.adminForm;
	cb = eval('f.' + cb);
	if (cb.checked == true) {
		cb.checked = false;
		document.adminForm.boxchecked.value--;
	} else {
		cb.checked = true;
		document.adminForm.boxchecked.value++;
	}
}


function submitform(pressbutton) {
	if (pressbutton) {
		document.adminForm.submit_option.value = pressbutton;
	}
	if (typeof document.adminForm.onsubmit == "function") {
		document.adminForm.onsubmit();
	}
	document.adminForm.submit();
}
//-->
</script>

<a 	href="javascript:void(0);" 
	onclick="if(document.adminForm.boxchecked.value==0) {    
		alert('Select at least one item.');}
		else {  submitform('delete')}">Delete</a> ..:..
<a href="<?php echo BASE_PATH . '/user/send-invitation'; ?>">Send invitation</a> ..:..
<form method="post" id="formAdmin" name="adminForm">

<input name="boxchecked" type="hidden" value="0" />
<input name="submit_option" value="" type="hidden" />

<table border="1">

<tfoot>
	<tr>
	<td colspan="11">
	<?php
																
	echo $this->paginationControl ( 
			$this->paginator, 
			'Sliding', 
			'partials/_pagination_control.phtml' );
	?>
	</td>
	</tr>
	</tfoot>
	<thead>
		<tr>
			<th width="2%" class="title">#</th>
			<th width="3%" class="title">
			<input type="checkbox" name="toggle"
				value="" onclick="checkAll(<?php echo $this->curPageCount; ?>);"></th>
			<th class="title">Name</th>

			

			<th width="10%" class="title">Email</th>

			<th width="4%">Date create</th>
			<th width="4%">Date update</th>

			<th width="1%" nowrap="nowrap" class="title">ID</th>
		</tr>
	</thead>
		
		
<?php

$i = 1;
foreach ( $this->paginator as $item => $val ) {
	
	$dateCreate = date ( "d-m-Y h:i:s", ( int ) ($val ['date_create']) );
	$dateUpdate = date ( "d-m-Y h:i:s", ( int ) ($val ['date_update']) );
	
	// $pg = new Cp_Model_UserGroup ();
	// $pg = $pg->find ( $val ['user_group_id'] )->current ();
	
	?>
<tr class="row0">
		<td style="cursor: pointer;"
			onclick="checkThis('cb<?php echo $i; ?>');">
    				    <?php echo $i; ?></td>
		<td><input type="checkbox" id="cb<?php echo $i; ?>" name="cid[]"
			value="<?php echo $val['user_id']; ?>"
			onclick="isChecked(this.checked);"></td>

		<td><a
			href="<?php echo $this->baseUrl('/user/edit/id/' . $val['user_id']); ?>">
    				    <?php echo $val['display_name']; ?></a></td>


		<td><?php echo $val['email']; ?></td>

		<td nowrap="nowrap"><?php echo $dateCreate; ?></td>

		<td nowrap="nowrap"><?php echo $dateUpdate; ?></td>

		<td><?php echo $val['user_id']; ?></td>
	</tr>
<?php
	$i ++;
}

?>

</table>
</form>