<h2>List all of Users</h2>
<hr />
<<script type="text/javascript">
<!--
/**
 * Toggles the check state of a group of boxes.
 * 
 * Checkboxes must have an id attribute in the form cb0, cb1...
 * 
 * @param The
 *            number of box to 'check'
 * @param An
 *            alternative field name
 */
function checkAll(n) {

	fldName = 'cb';

	var f = document.adminForm;
	var c = f.toggle.checked;
	var n2 = 0;
	for (i = 1; i <= n; i++) {
		cb = eval('f.' + fldName + '' + i);

		if (cb) {
			cb.checked = c;
			n2++;
		}

	}
	if (c) {
		document.adminForm.boxchecked.value = n2;
	} else {
		document.adminForm.boxchecked.value = 0;
	}
}
//-->
</script>
<form method="post" id="formAdmin">
<table border="1">

<tfoot>
	<tr>
	<td colspan="11">
	<?php
																
	echo $this->paginationControl ( 
			$this->paginator, 
			'Sliding', 
			'partials/_pagination_control.phtml' );
	?>
	</td>
	</tr>
	</tfoot>
	<thead>
		<tr>
			<th width="2%" class="title">#</th>
			<th width="3%" class="title"><input type="checkbox" name="toggle"
				value="" onclick="checkAll(<?php echo $this->curPageCount; ?>);"></th>
			<th class="title"><a
				href="javascript:tableOrdering('firstname','<?php echo $this->next_order_dir; ?>');">Tên</a></th>

			

			<th width="10%" class="title">Email</th>

			<th width="4%"><a
				href="javascript:tableOrdering('date_create','<?php echo $this->next_order_dir; ?>');">
					Ngày tạo</a></th>
			<th width="4%"><a
				href="javascript:tableOrdering('date_update','<?php echo $this->next_order_dir; ?>');">
					Ngày sửa</a></th>

			<th width="1%" nowrap="nowrap" class="title"><a
				href="javascript:tableOrdering('id','<?php echo $this->next_order_dir; ?>');"
				title="Nhấp chuột để sắp xếp theo cột này">ID</a></th>
		</tr>
	</thead>
		
		
<?php

$i = 1;
foreach ( $this->paginator as $item => $val ) {
	
	$dateCreate = date ( "d-m-Y h:i:s", ( int ) ($val ['date_create']) );
	$dateUpdate = date ( "d-m-Y h:i:s", ( int ) ($val ['date_update']) );
	
	// $pg = new Cp_Model_UserGroup ();
	// $pg = $pg->find ( $val ['user_group_id'] )->current ();
	
	?>
<tr class="row0">
		<td style="cursor: pointer;"
			onclick="checkThis('cb<?php echo $i; ?>');">
    				    <?php echo $i; ?></td>
		<td><input type="checkbox" id="cb<?php echo $i; ?>" name="cid[]"
			value="<?php echo $val['user_id']; ?>"
			onclick="isChecked(this.checked);"></td>

		<td><a
			href="<?php echo $this->baseUrl('cp/user/edit/id/' . $val['user_id']); ?>">
    				    <?php echo $val['display_name']; ?></a></td>


		<td><?php echo $val['email']; ?></td>

		<td nowrap="nowrap"><?php echo $dateCreate; ?></td>

		<td nowrap="nowrap"><?php echo $dateUpdate; ?></td>

		<td><?php echo $val['user_id']; ?></td>
	</tr>
<?php
	$i ++;
}

?>

</table>
</form>