<form enctype="<?php echo $this->element->getAttrib('enctype'); ?>" action='<?php echo $this->element->getAction(); ?>'
method= '<?php echo $this->element->getMethod(); ?>'>
<p>Old Image:<br />
<?php echo $this->element->imgOldImage; ?>
</p>
<p>Your Image:<br />
<?php echo $this->element->flPostPicture; ?>
</p>
<p>Your caption:<br />
<?php echo $this->element->txtPostCaption; ?>
</p>
<p>Display post :<br />
<?php echo $this->element->rdStatus; ?>
</p>
<p>
<?php 
echo $this->element->hdPostID;
echo $this->element->hdOldImage;
echo $this->element->btnSubmit; ?>
</p>
<input name="txtActionName" id="txtActionName" value="edit-step-2" type="text" style="display:none;" />
</form>
