<section id="main" class="column">
<?php 
	if(isset($_SESSION['post']['success']))
	{
		if($_SESSION['post']['success'] == 'add-success')
		{
			echo '<h4 class="alert_success">Add post success</h4>';
		}else if($_SESSION['post']['success'] == 'delete-success')
		{
			echo '<h4 class="alert_success">Delete post success</h4>'; 
		}
		unset($_SESSION['post']['success']);
	}else if(isset($_SESSION['post']['fail']))
	{
		if($_SESSION['post']['fail'] == 'delete-fail')
		{
			echo '<h4 class="alert_error">Delete post fail</h4>';  
		}
	}
?>
	
	<article class="module width_3_quarter">
	<header><h3 class="tabs_involved">Content Manager</h3>
		
	</header>
	<div class="tab_container">
		<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
				<thead> 
					<tr> 
	   					<th></th> 
	    				<th>Post picture</th> 
	    				<th>Office</th> 
	    				<th>Created On</th>
	    				<th>Actions</th> 
					</tr> 
				</thead> 
				<tbody>
				<?php 
				foreach($this->data as $item)
				{
					echo "<tr>"; 
	   				echo "<td><input type='checkbox'></td>";
	    			echo "<td><img src='" . THUMBNAIL_PATH . '/' . THUMBNAIL_NAME .$item['post_picture']."' /></td>";
	    			echo "<td>".$item['office_name']."</td>";
	    			$dateCreate = date( "m-d-Y h:i:s",(int)($item['post_time']));
	    			echo "<td>". $dateCreate ."</td>";
	    			echo "<td><input type='image' name='". $item['post_id'] ."' onClick='updateForm(this.name)' src='" . BASE_PATH . "/cp_templates/images/icn_edit.png' title='Edit'>";
					echo "<input type='image' name='". $item['post_id'] ."' onClick='deleteForm(". $item['post_id'] .",\"".$item['post_picture']."\")' src='" . BASE_PATH . "/cp_templates/images/icn_trash.png' title='Trash'></td>";
					echo "</tr>"; 
				}
				?>
				</tbody> 
			</table>
			<?php
			    echo $this->paginationControl($this->data, 'Sliding' , 'post/pagination.phtml'); 
			?>
		</div><!-- end of #tab1 -->
	</div>
		<input name="txtActionName" id="txtActionName" value="" type="text" style="display:none;" />
		<input name="txtPostImage" id="txtPostImage" value="" type="text" style="display:none;" />
		<input name="txtArticelID" id="txtArticelID" value="" type="text" style="display:none;" />
		<input id="btnSubmit" type="submit" value="submit" style="display:none;"/>
<script>
function updateForm(articelID){
	window.location.href = '<?php echo ADMINCP_PATH . '/post/edit/id/'?>' + articelID;
}
function deleteForm(articelID){
	window.location.href = '<?php echo ADMINCP_PATH . '/post/delete/id/'?>' + articelID;
}
</script>
</article>